# -*- coding: utf-8 -*-
"""
Created on Thu Dec 1 2016

OpenETran GUI Python file

@author: Matthieu
"""

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtCore import pyqtSlot
from collections import OrderedDict

#import Save, Simulate, Load, ReadStruct

class Ui_Tab(object):
    def setupUi(self, Tab):
        Tab.setObjectName("Tab")
        Tab.resize(1238, 1133)
        self.Project = QtWidgets.QWidget()
        self.Project.setObjectName("Project")
        self.load = QtWidgets.QPushButton(self.Project)
        self.load.setGeometry(QtCore.QRect(200, 80, 131, 41))
        self.load.setObjectName("load")
        self.save = QtWidgets.QPushButton(self.Project)
        self.save.setGeometry(QtCore.QRect(30, 80, 131, 41))
        self.save.setObjectName("save")
        self.newProjName = QtWidgets.QLineEdit(self.Project)
        self.newProjName.setGeometry(QtCore.QRect(450, 80, 261, 41))
        self.newProjName.setObjectName("newProjName")
        self.label = QtWidgets.QLabel(self.Project)
        self.label.setGeometry(QtCore.QRect(530, 40, 131, 31))
        self.label.setObjectName("label")
        Tab.addTab(self.Project, "")
        self.SystemView = QtWidgets.QWidget()
        self.SystemView.setObjectName("SystemView")
        self.sysView_label = QtWidgets.QLabel(self.SystemView)
        self.sysView_label.setGeometry(QtCore.QRect(10, 10, 121, 21))
        self.sysView_label.setObjectName("sysView_label")
        self.sysView = QtWidgets.QGraphicsView(self.SystemView)
        self.sysView.setGeometry(QtCore.QRect(10, 110, 1521, 751))
        self.sysView.setObjectName("sysView")
        self.drawSystem = QtWidgets.QPushButton(self.SystemView)
        self.drawSystem.setGeometry(QtCore.QRect(20, 40, 131, 51))
        self.drawSystem.setObjectName("drawSystem")
        Tab.addTab(self.SystemView, "")
        self.Simulation = QtWidgets.QWidget()
        self.Simulation.setObjectName("Simulation")
        self.numCond_label = QtWidgets.QLabel(self.Simulation)
        self.numCond_label.setGeometry(QtCore.QRect(10, 20, 171, 31))
        self.numCond_label.setObjectName("numCond_label")
        self.numPoles_label = QtWidgets.QLabel(self.Simulation)
        self.numPoles_label.setGeometry(QtCore.QRect(10, 80, 161, 31))
        self.numPoles_label.setObjectName("numPoles_label")
        self.lineSpan_label = QtWidgets.QLabel(self.Simulation)
        self.lineSpan_label.setGeometry(QtCore.QRect(10, 140, 161, 31))
        self.lineSpan_label.setObjectName("lineSpan_label")
        self.leftTerm_label = QtWidgets.QLabel(self.Simulation)
        self.leftTerm_label.setGeometry(QtCore.QRect(10, 200, 171, 31))
        self.leftTerm_label.setObjectName("leftTerm_label")
        self.rightTerm_label = QtWidgets.QLabel(self.Simulation)
        self.rightTerm_label.setGeometry(QtCore.QRect(10, 260, 191, 31))
        self.rightTerm_label.setObjectName("rightTerm_label")
        self.timeStep_label = QtWidgets.QLabel(self.Simulation)
        self.timeStep_label.setGeometry(QtCore.QRect(10, 320, 161, 31))
        self.timeStep_label.setObjectName("timeStep_label")
        self.simMax_label = QtWidgets.QLabel(self.Simulation)
        self.simMax_label.setGeometry(QtCore.QRect(10, 380, 201, 31))
        self.simMax_label.setObjectName("simMax_label")
        self.simButton = QtWidgets.QPushButton(self.Simulation)
        self.simButton.setGeometry(QtCore.QRect(410, 20, 151, 61))
        self.simButton.setObjectName("simButton")
        self.numCond = QtWidgets.QLineEdit(self.Simulation)
        self.numCond.setGeometry(QtCore.QRect(230, 20, 113, 31))
        self.numCond.setObjectName("numCond")
        self.numPoles = QtWidgets.QLineEdit(self.Simulation)
        self.numPoles.setGeometry(QtCore.QRect(230, 80, 113, 31))
        self.numPoles.setObjectName("numPoles")
        self.lineSpan = QtWidgets.QLineEdit(self.Simulation)
        self.lineSpan.setGeometry(QtCore.QRect(230, 140, 113, 31))
        self.lineSpan.setObjectName("lineSpan")
        self.leftTerm = QtWidgets.QLineEdit(self.Simulation)
        self.leftTerm.setGeometry(QtCore.QRect(230, 200, 113, 31))
        self.leftTerm.setObjectName("leftTerm")
        self.rightTerm = QtWidgets.QLineEdit(self.Simulation)
        self.rightTerm.setGeometry(QtCore.QRect(230, 260, 113, 31))
        self.rightTerm.setObjectName("rightTerm")
        self.timeStep = QtWidgets.QLineEdit(self.Simulation)
        self.timeStep.setGeometry(QtCore.QRect(230, 320, 113, 31))
        self.timeStep.setObjectName("timeStep")
        self.simMax = QtWidgets.QLineEdit(self.Simulation)
        self.simMax.setGeometry(QtCore.QRect(230, 380, 113, 31))
        self.simMax.setObjectName("simMax")
        Tab.addTab(self.Simulation, "")
        self.Conductor = QtWidgets.QWidget()
        self.Conductor.setObjectName("Conductor")
        self.cond1_label = QtWidgets.QLabel(self.Conductor)
        self.cond1_label.setGeometry(QtCore.QRect(10, 70, 101, 16))
        self.cond1_label.setObjectName("cond1_label")
        self.height1 = QtWidgets.QLineEdit(self.Conductor)
        self.height1.setGeometry(QtCore.QRect(220, 60, 113, 31))
        self.height1.setObjectName("height1")
        self.horPos1 = QtWidgets.QLineEdit(self.Conductor)
        self.horPos1.setGeometry(QtCore.QRect(380, 60, 113, 31))
        self.horPos1.setObjectName("horPos1")
        self.rad1 = QtWidgets.QLineEdit(self.Conductor)
        self.rad1.setGeometry(QtCore.QRect(540, 60, 113, 31))
        self.rad1.setObjectName("rad1")
        self.voltBias1 = QtWidgets.QLineEdit(self.Conductor)
        self.voltBias1.setGeometry(QtCore.QRect(700, 60, 113, 31))
        self.voltBias1.setObjectName("voltBias1")
        self.height_label = QtWidgets.QLabel(self.Conductor)
        self.height_label.setGeometry(QtCore.QRect(250, 30, 51, 21))
        self.height_label.setObjectName("height_label")
        self.horPos_label = QtWidgets.QLabel(self.Conductor)
        self.horPos_label.setGeometry(QtCore.QRect(350, 30, 171, 21))
        self.horPos_label.setObjectName("horPos_label")
        self.rad_label = QtWidgets.QLabel(self.Conductor)
        self.rad_label.setGeometry(QtCore.QRect(550, 30, 91, 21))
        self.rad_label.setObjectName("rad_label")
        self.voltBias_label = QtWidgets.QLabel(self.Conductor)
        self.voltBias_label.setGeometry(QtCore.QRect(700, 30, 121, 21))
        self.voltBias_label.setObjectName("voltBias_label")
        self.height2 = QtWidgets.QLineEdit(self.Conductor)
        self.height2.setGeometry(QtCore.QRect(220, 120, 113, 31))
        self.height2.setObjectName("height2")
        self.horPos2 = QtWidgets.QLineEdit(self.Conductor)
        self.horPos2.setGeometry(QtCore.QRect(380, 120, 113, 31))
        self.horPos2.setObjectName("horPos2")
        self.voltBias2 = QtWidgets.QLineEdit(self.Conductor)
        self.voltBias2.setGeometry(QtCore.QRect(700, 120, 113, 31))
        self.voltBias2.setObjectName("voltBias2")
        self.rad2 = QtWidgets.QLineEdit(self.Conductor)
        self.rad2.setGeometry(QtCore.QRect(540, 120, 113, 31))
        self.rad2.setObjectName("rad2")
        self.cond2_label = QtWidgets.QLabel(self.Conductor)
        self.cond2_label.setGeometry(QtCore.QRect(10, 130, 91, 16))
        self.cond2_label.setObjectName("cond2_label")
        self.height3 = QtWidgets.QLineEdit(self.Conductor)
        self.height3.setGeometry(QtCore.QRect(220, 180, 113, 31))
        self.height3.setObjectName("height3")
        self.horPos3 = QtWidgets.QLineEdit(self.Conductor)
        self.horPos3.setGeometry(QtCore.QRect(380, 180, 113, 31))
        self.horPos3.setObjectName("horPos3")
        self.voltBias3 = QtWidgets.QLineEdit(self.Conductor)
        self.voltBias3.setGeometry(QtCore.QRect(700, 180, 113, 31))
        self.voltBias3.setObjectName("voltBias3")
        self.rad3 = QtWidgets.QLineEdit(self.Conductor)
        self.rad3.setGeometry(QtCore.QRect(540, 180, 113, 31))
        self.rad3.setObjectName("rad3")
        self.cond3_label = QtWidgets.QLabel(self.Conductor)
        self.cond3_label.setGeometry(QtCore.QRect(10, 190, 91, 16))
        self.cond3_label.setObjectName("cond3_label")
        self.height4 = QtWidgets.QLineEdit(self.Conductor)
        self.height4.setGeometry(QtCore.QRect(220, 240, 113, 31))
        self.height4.setObjectName("height4")
        self.horPos4 = QtWidgets.QLineEdit(self.Conductor)
        self.horPos4.setGeometry(QtCore.QRect(380, 240, 113, 31))
        self.horPos4.setObjectName("horPos4")
        self.voltBias4 = QtWidgets.QLineEdit(self.Conductor)
        self.voltBias4.setGeometry(QtCore.QRect(700, 240, 113, 31))
        self.voltBias4.setObjectName("voltBias4")
        self.rad4 = QtWidgets.QLineEdit(self.Conductor)
        self.rad4.setGeometry(QtCore.QRect(540, 240, 113, 31))
        self.rad4.setObjectName("rad4")
        self.cond4_label = QtWidgets.QLabel(self.Conductor)
        self.cond4_label.setGeometry(QtCore.QRect(10, 250, 171, 16))
        self.cond4_label.setObjectName("cond4_label")
        self.label4 = QtWidgets.QLineEdit(self.Conductor)
        self.label4.setGeometry(QtCore.QRect(860, 240, 113, 31))
        self.label4.setObjectName("label4")
        self.condLabel_label = QtWidgets.QLabel(self.Conductor)
        self.condLabel_label.setGeometry(QtCore.QRect(870, 30, 91, 21))
        self.condLabel_label.setObjectName("condLabel_label")
        self.label3 = QtWidgets.QLineEdit(self.Conductor)
        self.label3.setGeometry(QtCore.QRect(860, 180, 113, 31))
        self.label3.setObjectName("label3")
        self.label2 = QtWidgets.QLineEdit(self.Conductor)
        self.label2.setGeometry(QtCore.QRect(860, 120, 113, 31))
        self.label2.setObjectName("label2")
        self.label1 = QtWidgets.QLineEdit(self.Conductor)
        self.label1.setGeometry(QtCore.QRect(860, 60, 113, 31))
        self.label1.setObjectName("label1")
        Tab.addTab(self.Conductor, "")
        self.Ground = QtWidgets.QWidget()
        self.Ground.setObjectName("Ground")
        self.ground1_label = QtWidgets.QLabel(self.Ground)
        self.ground1_label.setGeometry(QtCore.QRect(20, 110, 71, 31))
        self.ground1_label.setObjectName("ground1_label")
        self.r60Ground1 = QtWidgets.QLineEdit(self.Ground)
        self.r60Ground1.setGeometry(QtCore.QRect(140, 110, 113, 31))
        self.r60Ground1.setObjectName("r60Ground1")
        self.resistGround1 = QtWidgets.QLineEdit(self.Ground)
        self.resistGround1.setGeometry(QtCore.QRect(350, 110, 113, 31))
        self.resistGround1.setObjectName("resistGround1")
        self.brkGround1 = QtWidgets.QLineEdit(self.Ground)
        self.brkGround1.setGeometry(QtCore.QRect(560, 110, 113, 31))
        self.brkGround1.setObjectName("brkGround1")
        self.dwnLGround1 = QtWidgets.QLineEdit(self.Ground)
        self.dwnLGround1.setGeometry(QtCore.QRect(770, 110, 113, 31))
        self.dwnLGround1.setObjectName("dwnLGround1")
        self.dwnLengthGround1 = QtWidgets.QLineEdit(self.Ground)
        self.dwnLengthGround1.setGeometry(QtCore.QRect(980, 110, 113, 31))
        self.dwnLengthGround1.setObjectName("dwnLengthGround1")
        self.r60Ground_label = QtWidgets.QLabel(self.Ground)
        self.r60Ground_label.setGeometry(QtCore.QRect(140, 80, 111, 20))
        self.r60Ground_label.setObjectName("r60Ground_label")
        self.resistGround_label = QtWidgets.QLabel(self.Ground)
        self.resistGround_label.setGeometry(QtCore.QRect(320, 80, 191, 20))
        self.resistGround_label.setObjectName("resistGround_label")
        self.brkGround_label = QtWidgets.QLabel(self.Ground)
        self.brkGround_label.setGeometry(QtCore.QRect(530, 80, 181, 20))
        self.brkGround_label.setObjectName("brkGround_label")
        self.dwnLGround_label = QtWidgets.QLabel(self.Ground)
        self.dwnLGround_label.setGeometry(QtCore.QRect(720, 80, 211, 20))
        self.dwnLGround_label.setObjectName("dwnLGround_label")
        self.dwnLengthGround_label = QtWidgets.QLabel(self.Ground)
        self.dwnLengthGround_label.setGeometry(QtCore.QRect(950, 80, 181, 20))
        self.dwnLengthGround_label.setObjectName("dwnLengthGround_label")
        self.radGround1 = QtWidgets.QLineEdit(self.Ground)
        self.radGround1.setGeometry(QtCore.QRect(140, 200, 113, 31))
        self.radGround1.setObjectName("radGround1")
        self.radGround_label = QtWidgets.QLabel(self.Ground)
        self.radGround_label.setGeometry(QtCore.QRect(110, 170, 191, 20))
        self.radGround_label.setObjectName("radGround_label")
        self.depthGround1 = QtWidgets.QLineEdit(self.Ground)
        self.depthGround1.setGeometry(QtCore.QRect(350, 200, 113, 31))
        self.depthGround1.setObjectName("depthGround1")
        self.depthGround_label = QtWidgets.QLabel(self.Ground)
        self.depthGround_label.setGeometry(QtCore.QRect(330, 170, 181, 20))
        self.depthGround_label.setObjectName("depthGround_label")
        self.lengthGround1 = QtWidgets.QLineEdit(self.Ground)
        self.lengthGround1.setGeometry(QtCore.QRect(560, 200, 113, 31))
        self.lengthGround1.setObjectName("lengthGround1")
        self.lengthGround_label = QtWidgets.QLabel(self.Ground)
        self.lengthGround_label.setGeometry(QtCore.QRect(530, 170, 191, 20))
        self.lengthGround_label.setObjectName("lengthGround_label")
        self.numSegGround1 = QtWidgets.QLineEdit(self.Ground)
        self.numSegGround1.setGeometry(QtCore.QRect(770, 200, 113, 31))
        self.numSegGround1.setObjectName("numSegGround1")
        self.numSegGround_label = QtWidgets.QLabel(self.Ground)
        self.numSegGround_label.setGeometry(QtCore.QRect(750, 170, 161, 20))
        self.numSegGround_label.setObjectName("numSegGround_label")
        self.permGround1 = QtWidgets.QLineEdit(self.Ground)
        self.permGround1.setGeometry(QtCore.QRect(980, 200, 113, 31))
        self.permGround1.setObjectName("permGround1")
        self.permGround_label = QtWidgets.QLabel(self.Ground)
        self.permGround_label.setGeometry(QtCore.QRect(940, 170, 181, 20))
        self.permGround_label.setObjectName("permGround_label")
        self.pairGround1 = QtWidgets.QLineEdit(self.Ground)
        self.pairGround1.setGeometry(QtCore.QRect(140, 290, 113, 31))
        self.pairGround1.setObjectName("pairGround1")
        self.pairGround_label = QtWidgets.QLabel(self.Ground)
        self.pairGround_label.setGeometry(QtCore.QRect(140, 260, 111, 20))
        self.pairGround_label.setObjectName("pairGround_label")
        self.poleGround1 = QtWidgets.QLineEdit(self.Ground)
        self.poleGround1.setGeometry(QtCore.QRect(350, 290, 113, 31))
        self.poleGround1.setObjectName("poleGround1")
        self.poleGround_label = QtWidgets.QLabel(self.Ground)
        self.poleGround_label.setGeometry(QtCore.QRect(350, 260, 111, 20))
        self.poleGround_label.setObjectName("poleGround_label")
        self.newGround = QtWidgets.QPushButton(self.Ground)
        self.newGround.setGeometry(QtCore.QRect(10, 20, 91, 41))
        self.newGround.setObjectName("newGround")
        Tab.addTab(self.Ground, "")
        self.Surge = QtWidgets.QWidget()
        self.Surge.setObjectName("Surge")
        self.crestSurge_label = QtWidgets.QLabel(self.Surge)
        self.crestSurge_label.setGeometry(QtCore.QRect(10, 30, 141, 31))
        self.crestSurge_label.setObjectName("crestSurge_label")
        self.crestSurge = QtWidgets.QLineEdit(self.Surge)
        self.crestSurge.setGeometry(QtCore.QRect(240, 30, 113, 31))
        self.crestSurge.setObjectName("crestSurge")
        self.frontSurge_label = QtWidgets.QLabel(self.Surge)
        self.frontSurge_label.setGeometry(QtCore.QRect(10, 90, 171, 31))
        self.frontSurge_label.setObjectName("frontSurge_label")
        self.frontSurge = QtWidgets.QLineEdit(self.Surge)
        self.frontSurge.setGeometry(QtCore.QRect(240, 90, 113, 31))
        self.frontSurge.setObjectName("frontSurge")
        self.tailSurge_label = QtWidgets.QLabel(self.Surge)
        self.tailSurge_label.setGeometry(QtCore.QRect(10, 150, 161, 31))
        self.tailSurge_label.setObjectName("tailSurge_label")
        self.tailSurge = QtWidgets.QLineEdit(self.Surge)
        self.tailSurge.setGeometry(QtCore.QRect(240, 150, 113, 31))
        self.tailSurge.setObjectName("tailSurge")
        self.startSurge_label = QtWidgets.QLabel(self.Surge)
        self.startSurge_label.setGeometry(QtCore.QRect(10, 210, 181, 31))
        self.startSurge_label.setObjectName("startSurge_label")
        self.startSurge = QtWidgets.QLineEdit(self.Surge)
        self.startSurge.setGeometry(QtCore.QRect(240, 210, 113, 31))
        self.startSurge.setObjectName("startSurge")
        self.maxSurge_label = QtWidgets.QLabel(self.Surge)
        self.maxSurge_label.setGeometry(QtCore.QRect(10, 270, 211, 31))
        self.maxSurge_label.setObjectName("maxSurge_label")
        self.maxSurge = QtWidgets.QLineEdit(self.Surge)
        self.maxSurge.setGeometry(QtCore.QRect(240, 270, 113, 31))
        self.maxSurge.setObjectName("maxSurge")
        Tab.addTab(self.Surge, "")
        self.Steepfront = QtWidgets.QWidget()
        self.Steepfront.setObjectName("Steepfront")
        self.tailSteep = QtWidgets.QLineEdit(self.Steepfront)
        self.tailSteep.setGeometry(QtCore.QRect(240, 150, 113, 31))
        self.tailSteep.setObjectName("tailSteep")
        self.crestSteep_label = QtWidgets.QLabel(self.Steepfront)
        self.crestSteep_label.setGeometry(QtCore.QRect(10, 30, 141, 31))
        self.crestSteep_label.setObjectName("crestSteep_label")
        self.maxSteep = QtWidgets.QLineEdit(self.Steepfront)
        self.maxSteep.setGeometry(QtCore.QRect(240, 270, 113, 31))
        self.maxSteep.setObjectName("maxSteep")
        self.frontSteep_label = QtWidgets.QLabel(self.Steepfront)
        self.frontSteep_label.setGeometry(QtCore.QRect(10, 90, 171, 31))
        self.frontSteep_label.setObjectName("frontSteep_label")
        self.startSteep_label = QtWidgets.QLabel(self.Steepfront)
        self.startSteep_label.setGeometry(QtCore.QRect(10, 210, 181, 31))
        self.startSteep_label.setObjectName("startSteep_label")
        self.startSteep = QtWidgets.QLineEdit(self.Steepfront)
        self.startSteep.setGeometry(QtCore.QRect(240, 210, 113, 31))
        self.startSteep.setObjectName("startSteep")
        self.tailSteep_label = QtWidgets.QLabel(self.Steepfront)
        self.tailSteep_label.setGeometry(QtCore.QRect(10, 150, 161, 31))
        self.tailSteep_label.setObjectName("tailSteep_label")
        self.frontSteep_label_2 = QtWidgets.QLineEdit(self.Steepfront)
        self.frontSteep_label_2.setGeometry(QtCore.QRect(240, 90, 113, 31))
        self.frontSteep_label_2.setObjectName("frontSteep_label_2")
        self.crestSteep = QtWidgets.QLineEdit(self.Steepfront)
        self.crestSteep.setGeometry(QtCore.QRect(240, 30, 113, 31))
        self.crestSteep.setObjectName("crestSteep")
        self.maxSteep_label = QtWidgets.QLabel(self.Steepfront)
        self.maxSteep_label.setGeometry(QtCore.QRect(10, 270, 211, 31))
        self.maxSteep_label.setObjectName("maxSteep_label")
        Tab.addTab(self.Steepfront, "")
        self.Arrester = QtWidgets.QWidget()
        self.Arrester.setObjectName("Arrester")
        self.newArrester = QtWidgets.QPushButton(self.Arrester)
        self.newArrester.setGeometry(QtCore.QRect(10, 20, 91, 41))
        self.newArrester.setObjectName("newArrester")
        self.arrester1_label = QtWidgets.QLabel(self.Arrester)
        self.arrester1_label.setGeometry(QtCore.QRect(20, 110, 91, 31))
        self.arrester1_label.setObjectName("arrester1_label")
        self.spVoltArr1 = QtWidgets.QLineEdit(self.Arrester)
        self.spVoltArr1.setGeometry(QtCore.QRect(150, 110, 113, 31))
        self.spVoltArr1.setObjectName("spVoltArr1")
        self.spVoltArr1_label = QtWidgets.QLabel(self.Arrester)
        self.spVoltArr1_label.setGeometry(QtCore.QRect(130, 70, 171, 31))
        self.spVoltArr1_label.setObjectName("spVoltArr1_label")
        self.tOnArr1 = QtWidgets.QLineEdit(self.Arrester)
        self.tOnArr1.setGeometry(QtCore.QRect(350, 110, 113, 31))
        self.tOnArr1.setObjectName("tOnArr1")
        self.tOnArr1_label = QtWidgets.QLabel(self.Arrester)
        self.tOnArr1_label.setGeometry(QtCore.QRect(330, 70, 151, 31))
        self.tOnArr1_label.setObjectName("tOnArr1_label")
        self.disArr1 = QtWidgets.QLineEdit(self.Arrester)
        self.disArr1.setGeometry(QtCore.QRect(550, 110, 113, 31))
        self.disArr1.setObjectName("disArr1")
        self.disArr1_label = QtWidgets.QLabel(self.Arrester)
        self.disArr1_label.setGeometry(QtCore.QRect(490, 70, 241, 31))
        self.disArr1_label.setObjectName("disArr1_label")
        self.indArr1 = QtWidgets.QLineEdit(self.Arrester)
        self.indArr1.setGeometry(QtCore.QRect(750, 110, 113, 31))
        self.indArr1.setObjectName("indArr1")
        self.indArr1_label = QtWidgets.QLabel(self.Arrester)
        self.indArr1_label.setGeometry(QtCore.QRect(740, 70, 191, 31))
        self.indArr1_label.setObjectName("indArr1_label")
        self.lengthArr1 = QtWidgets.QLineEdit(self.Arrester)
        self.lengthArr1.setGeometry(QtCore.QRect(950, 110, 113, 31))
        self.lengthArr1.setObjectName("lengthArr1")
        self.lengthArr1_label = QtWidgets.QLabel(self.Arrester)
        self.lengthArr1_label.setGeometry(QtCore.QRect(940, 70, 141, 31))
        self.lengthArr1_label.setObjectName("lengthArr1_label")
        self.pairArr1 = QtWidgets.QLineEdit(self.Arrester)
        self.pairArr1.setGeometry(QtCore.QRect(150, 200, 113, 31))
        self.pairArr1.setObjectName("pairArr1")
        self.pairArr1_label = QtWidgets.QLabel(self.Arrester)
        self.pairArr1_label.setGeometry(QtCore.QRect(150, 170, 111, 20))
        self.pairArr1_label.setObjectName("pairArr1_label")
        self.poleArr1 = QtWidgets.QLineEdit(self.Arrester)
        self.poleArr1.setGeometry(QtCore.QRect(350, 200, 113, 31))
        self.poleArr1.setObjectName("poleArr1")
        self.poleArr1_label = QtWidgets.QLabel(self.Arrester)
        self.poleArr1_label.setGeometry(QtCore.QRect(350, 170, 111, 20))
        self.poleArr1_label.setObjectName("poleArr1_label")
        Tab.addTab(self.Arrester, "")
        self.Arrbez = QtWidgets.QWidget()
        self.Arrbez.setObjectName("Arrbez")
        self.spVoltArrb1 = QtWidgets.QLineEdit(self.Arrbez)
        self.spVoltArrb1.setGeometry(QtCore.QRect(160, 110, 113, 31))
        self.spVoltArrb1.setObjectName("spVoltArrb1")
        self.refVoltArrb1_label = QtWidgets.QLabel(self.Arrbez)
        self.refVoltArrb1_label.setGeometry(QtCore.QRect(520, 70, 181, 31))
        self.refVoltArrb1_label.setObjectName("refVoltArrb1_label")
        self.poleArrb1 = QtWidgets.QLineEdit(self.Arrbez)
        self.poleArrb1.setGeometry(QtCore.QRect(350, 210, 113, 31))
        self.poleArrb1.setObjectName("poleArrb1")
        self.poleArrb1_label = QtWidgets.QLabel(self.Arrbez)
        self.poleArrb1_label.setGeometry(QtCore.QRect(350, 170, 81, 31))
        self.poleArrb1_label.setObjectName("poleArrb1_label")
        self.refVoltArrb1 = QtWidgets.QLineEdit(self.Arrbez)
        self.refVoltArrb1.setGeometry(QtCore.QRect(540, 110, 113, 31))
        self.refVoltArrb1.setObjectName("refVoltArrb1")
        self.indArrb1 = QtWidgets.QLineEdit(self.Arrbez)
        self.indArrb1.setGeometry(QtCore.QRect(730, 110, 113, 31))
        self.indArrb1.setObjectName("indArrb1")
        self.indArrb1_label = QtWidgets.QLabel(self.Arrbez)
        self.indArrb1_label.setGeometry(QtCore.QRect(700, 70, 191, 31))
        self.indArrb1_label.setObjectName("indArrb1_label")
        self.newArrbez = QtWidgets.QPushButton(self.Arrbez)
        self.newArrbez.setGeometry(QtCore.QRect(10, 20, 91, 41))
        self.newArrbez.setObjectName("newArrbez")
        self.pairArrb1 = QtWidgets.QLineEdit(self.Arrbez)
        self.pairArrb1.setGeometry(QtCore.QRect(160, 211, 113, 31))
        self.pairArrb1.setObjectName("pairArrb1")
        self.arrbez1_label = QtWidgets.QLabel(self.Arrbez)
        self.arrbez1_label.setGeometry(QtCore.QRect(20, 110, 81, 31))
        self.arrbez1_label.setObjectName("arrbez1_label")
        self.lengthArrb1 = QtWidgets.QLineEdit(self.Arrbez)
        self.lengthArrb1.setGeometry(QtCore.QRect(930, 110, 113, 31))
        self.lengthArrb1.setObjectName("lengthArrb1")
        self.lengthArrb1_label = QtWidgets.QLabel(self.Arrbez)
        self.lengthArrb1_label.setGeometry(QtCore.QRect(910, 70, 151, 31))
        self.lengthArrb1_label.setObjectName("lengthArrb1_label")
        self.pairArrb1_label = QtWidgets.QLabel(self.Arrbez)
        self.pairArrb1_label.setGeometry(QtCore.QRect(160, 170, 81, 31))
        self.pairArrb1_label.setObjectName("pairArrb1_label")
        self.spVoltArrb1_label = QtWidgets.QLabel(self.Arrbez)
        self.spVoltArrb1_label.setGeometry(QtCore.QRect(140, 70, 161, 31))
        self.spVoltArrb1_label.setObjectName("spVoltArrb1_label")
        self.disVoltArrb1 = QtWidgets.QLineEdit(self.Arrbez)
        self.disVoltArrb1.setGeometry(QtCore.QRect(350, 110, 113, 31))
        self.disVoltArrb1.setObjectName("disVoltArrb1")
        self.disVoltArrb1_label = QtWidgets.QLabel(self.Arrbez)
        self.disVoltArrb1_label.setGeometry(QtCore.QRect(310, 70, 201, 31))
        self.disVoltArrb1_label.setObjectName("disVoltArrb1_label")
        self.plotArrb1_label = QtWidgets.QLabel(self.Arrbez)
        self.plotArrb1_label.setGeometry(QtCore.QRect(540, 160, 161, 41))
        self.plotArrb1_label.setObjectName("plotArrb1_label")
        self.plotArrb1 = QtWidgets.QComboBox(self.Arrbez)
        self.plotArrb1.setGeometry(QtCore.QRect(540, 210, 151, 31))
        self.plotArrb1.setObjectName("plotArrb1")
        self.plotArrb1.addItem("")
        self.plotArrb1.addItem("")
        Tab.addTab(self.Arrbez, "")
        self.Insulator = QtWidgets.QWidget()
        self.Insulator.setObjectName("Insulator")
        self.newInsulator = QtWidgets.QPushButton(self.Insulator)
        self.newInsulator.setGeometry(QtCore.QRect(10, 20, 91, 41))
        self.newInsulator.setObjectName("newInsulator")
        self.minVoltIns1 = QtWidgets.QLineEdit(self.Insulator)
        self.minVoltIns1.setGeometry(QtCore.QRect(180, 110, 113, 31))
        self.minVoltIns1.setObjectName("minVoltIns1")
        self.insulator1_label = QtWidgets.QLabel(self.Insulator)
        self.insulator1_label.setGeometry(QtCore.QRect(20, 110, 91, 31))
        self.insulator1_label.setObjectName("insulator1_label")
        self.minVoltIns1_label = QtWidgets.QLabel(self.Insulator)
        self.minVoltIns1_label.setGeometry(QtCore.QRect(110, 70, 241, 31))
        self.minVoltIns1_label.setObjectName("minVoltIns1_label")
        self.minDesIns1_label = QtWidgets.QLabel(self.Insulator)
        self.minDesIns1_label.setGeometry(QtCore.QRect(630, 70, 311, 31))
        self.minDesIns1_label.setObjectName("minDesIns1_label")
        self.expIns1 = QtWidgets.QLineEdit(self.Insulator)
        self.expIns1.setGeometry(QtCore.QRect(440, 111, 113, 31))
        self.expIns1.setObjectName("expIns1")
        self.expIns1_label = QtWidgets.QLabel(self.Insulator)
        self.expIns1_label.setGeometry(QtCore.QRect(360, 70, 251, 31))
        self.expIns1_label.setObjectName("expIns1_label")
        self.cfoIns1 = QtWidgets.QLineEdit(self.Insulator)
        self.cfoIns1.setGeometry(QtCore.QRect(180, 210, 113, 31))
        self.cfoIns1.setObjectName("cfoIns1")
        self.minDesIns1 = QtWidgets.QLineEdit(self.Insulator)
        self.minDesIns1.setGeometry(QtCore.QRect(730, 110, 113, 31))
        self.minDesIns1.setObjectName("minDesIns1")
        self.cfoIns1_label = QtWidgets.QLabel(self.Insulator)
        self.cfoIns1_label.setGeometry(QtCore.QRect(180, 180, 81, 21))
        self.cfoIns1_label.setObjectName("cfoIns1_label")
        self.pairIns1_label = QtWidgets.QLabel(self.Insulator)
        self.pairIns1_label.setGeometry(QtCore.QRect(440, 170, 81, 31))
        self.pairIns1_label.setObjectName("pairIns1_label")
        self.poleIns1 = QtWidgets.QLineEdit(self.Insulator)
        self.poleIns1.setGeometry(QtCore.QRect(730, 210, 113, 31))
        self.poleIns1.setObjectName("poleIns1")
        self.pairIns1 = QtWidgets.QLineEdit(self.Insulator)
        self.pairIns1.setGeometry(QtCore.QRect(440, 210, 113, 31))
        self.pairIns1.setObjectName("pairIns1")
        self.poleIns1_label = QtWidgets.QLabel(self.Insulator)
        self.poleIns1_label.setGeometry(QtCore.QRect(730, 170, 81, 31))
        self.poleIns1_label.setObjectName("poleIns1_label")
        Tab.addTab(self.Insulator, "")
        self.LPM = QtWidgets.QWidget()
        self.LPM.setObjectName("LPM")
        self.newLPM = QtWidgets.QPushButton(self.LPM)
        self.newLPM.setGeometry(QtCore.QRect(10, 20, 91, 41))
        self.newLPM.setObjectName("newLPM")
        self.cstLPM1 = QtWidgets.QLineEdit(self.LPM)
        self.cstLPM1.setGeometry(QtCore.QRect(570, 110, 113, 31))
        self.cstLPM1.setObjectName("cstLPM1")
        self.pairLPM1_label = QtWidgets.QLabel(self.LPM)
        self.pairLPM1_label.setGeometry(QtCore.QRect(170, 170, 81, 31))
        self.pairLPM1_label.setObjectName("pairLPM1_label")
        self.poleLPM1_label = QtWidgets.QLabel(self.LPM)
        self.poleLPM1_label.setGeometry(QtCore.QRect(380, 170, 81, 31))
        self.poleLPM1_label.setObjectName("poleLPM1_label")
        self.poleLPM1 = QtWidgets.QLineEdit(self.LPM)
        self.poleLPM1.setGeometry(QtCore.QRect(380, 210, 113, 31))
        self.poleLPM1.setObjectName("poleLPM1")
        self.brkLPM1 = QtWidgets.QLineEdit(self.LPM)
        self.brkLPM1.setGeometry(QtCore.QRect(370, 110, 113, 31))
        self.brkLPM1.setObjectName("brkLPM1")
        self.cfoLPM1 = QtWidgets.QLineEdit(self.LPM)
        self.cfoLPM1.setGeometry(QtCore.QRect(170, 110, 113, 31))
        self.cfoLPM1.setObjectName("cfoLPM1")
        self.cfoLPM1_label = QtWidgets.QLabel(self.LPM)
        self.cfoLPM1_label.setGeometry(QtCore.QRect(170, 70, 111, 31))
        self.cfoLPM1_label.setObjectName("cfoLPM1_label")
        self.lpm1_label = QtWidgets.QLabel(self.LPM)
        self.lpm1_label.setGeometry(QtCore.QRect(30, 110, 61, 31))
        self.lpm1_label.setObjectName("lpm1_label")
        self.pairLPM1 = QtWidgets.QLineEdit(self.LPM)
        self.pairLPM1.setGeometry(QtCore.QRect(170, 210, 113, 31))
        self.pairLPM1.setObjectName("pairLPM1")
        self.cstLPM1_label = QtWidgets.QLabel(self.LPM)
        self.cstLPM1_label.setGeometry(QtCore.QRect(560, 70, 131, 31))
        self.cstLPM1_label.setObjectName("cstLPM1_label")
        self.brkLPM1_label = QtWidgets.QLabel(self.LPM)
        self.brkLPM1_label.setGeometry(QtCore.QRect(340, 70, 181, 31))
        self.brkLPM1_label.setObjectName("brkLPM1_label")
        Tab.addTab(self.LPM, "")
        self.Meters = QtWidgets.QWidget()
        self.Meters.setObjectName("Meters")
        self.meter1_label = QtWidgets.QLabel(self.Meters)
        self.meter1_label.setGeometry(QtCore.QRect(20, 110, 71, 31))
        self.meter1_label.setObjectName("meter1_label")
        self.newMeter = QtWidgets.QPushButton(self.Meters)
        self.newMeter.setGeometry(QtCore.QRect(10, 20, 91, 41))
        self.newMeter.setObjectName("newMeter")
        self.typeMeter1_label = QtWidgets.QLabel(self.Meters)
        self.typeMeter1_label.setGeometry(QtCore.QRect(130, 70, 71, 31))
        self.typeMeter1_label.setObjectName("typeMeter1_label")
        self.typeMeter1 = QtWidgets.QComboBox(self.Meters)
        self.typeMeter1.setGeometry(QtCore.QRect(130, 110, 331, 31))
        self.typeMeter1.setObjectName("typeMeter1")
        self.typeMeter1.addItem("")
        self.typeMeter1.addItem("")
        self.typeMeter1.addItem("")
        self.typeMeter1.addItem("")
        self.typeMeter1.addItem("")
        self.typeMeter1.addItem("")
        self.pairMeter1 = QtWidgets.QLineEdit(self.Meters)
        self.pairMeter1.setGeometry(QtCore.QRect(480, 110, 113, 31))
        self.pairMeter1.setObjectName("pairMeter1")
        self.pairMeter1_label = QtWidgets.QLabel(self.Meters)
        self.pairMeter1_label.setGeometry(QtCore.QRect(480, 70, 111, 31))
        self.pairMeter1_label.setObjectName("pairMeter1_label")
        self.poleMeter1_label = QtWidgets.QLabel(self.Meters)
        self.poleMeter1_label.setGeometry(QtCore.QRect(610, 70, 101, 31))
        self.poleMeter1_label.setObjectName("poleMeter1_label")
        self.poleMeter1 = QtWidgets.QLineEdit(self.Meters)
        self.poleMeter1.setGeometry(QtCore.QRect(610, 110, 113, 31))
        self.poleMeter1.setObjectName("poleMeter1")
        Tab.addTab(self.Meters, "")
        self.Resistors = QtWidgets.QWidget()
        self.Resistors.setObjectName("Resistors")
        self.valRes1_label = QtWidgets.QLabel(self.Resistors)
        self.valRes1_label.setGeometry(QtCore.QRect(190, 79, 111, 31))
        self.valRes1_label.setObjectName("valRes1_label")
        self.pairRes1_label = QtWidgets.QLabel(self.Resistors)
        self.pairRes1_label.setGeometry(QtCore.QRect(180, 160, 91, 20))
        self.pairRes1_label.setObjectName("pairRes1_label")
        self.resistor1_label = QtWidgets.QLabel(self.Resistors)
        self.resistor1_label.setGeometry(QtCore.QRect(20, 110, 91, 31))
        self.resistor1_label.setObjectName("resistor1_label")
        self.valRes1 = QtWidgets.QLineEdit(self.Resistors)
        self.valRes1.setGeometry(QtCore.QRect(180, 110, 113, 31))
        self.valRes1.setObjectName("valRes1")
        self.pairRes1 = QtWidgets.QLineEdit(self.Resistors)
        self.pairRes1.setGeometry(QtCore.QRect(180, 190, 113, 31))
        self.pairRes1.setObjectName("pairRes1")
        self.poleRes1 = QtWidgets.QLineEdit(self.Resistors)
        self.poleRes1.setGeometry(QtCore.QRect(310, 190, 113, 31))
        self.poleRes1.setObjectName("poleRes1")
        self.poleRes1_label = QtWidgets.QLabel(self.Resistors)
        self.poleRes1_label.setGeometry(QtCore.QRect(310, 160, 91, 20))
        self.poleRes1_label.setObjectName("poleRes1_label")
        self.newResistor = QtWidgets.QPushButton(self.Resistors)
        self.newResistor.setGeometry(QtCore.QRect(10, 20, 91, 41))
        self.newResistor.setObjectName("newResistor")
        Tab.addTab(self.Resistors, "")
        self.Inductors = QtWidgets.QWidget()
        self.Inductors.setObjectName("Inductors")
        self.valInd1_label = QtWidgets.QLabel(self.Inductors)
        self.valInd1_label.setGeometry(QtCore.QRect(150, 80, 171, 31))
        self.valInd1_label.setObjectName("valInd1_label")
        self.pairInd1_label = QtWidgets.QLabel(self.Inductors)
        self.pairInd1_label.setGeometry(QtCore.QRect(170, 169, 81, 31))
        self.pairInd1_label.setObjectName("pairInd1_label")
        self.inductor1_label = QtWidgets.QLabel(self.Inductors)
        self.inductor1_label.setGeometry(QtCore.QRect(20, 110, 101, 31))
        self.inductor1_label.setObjectName("inductor1_label")
        self.valInd1 = QtWidgets.QLineEdit(self.Inductors)
        self.valInd1.setGeometry(QtCore.QRect(170, 120, 113, 31))
        self.valInd1.setObjectName("valInd1")
        self.pairInd1 = QtWidgets.QLineEdit(self.Inductors)
        self.pairInd1.setGeometry(QtCore.QRect(170, 210, 113, 31))
        self.pairInd1.setObjectName("pairInd1")
        self.poleInd1 = QtWidgets.QLineEdit(self.Inductors)
        self.poleInd1.setGeometry(QtCore.QRect(380, 210, 113, 31))
        self.poleInd1.setObjectName("poleInd1")
        self.poleInd1_label = QtWidgets.QLabel(self.Inductors)
        self.poleInd1_label.setGeometry(QtCore.QRect(380, 169, 81, 31))
        self.poleInd1_label.setObjectName("poleInd1_label")
        self.newInductor = QtWidgets.QPushButton(self.Inductors)
        self.newInductor.setGeometry(QtCore.QRect(10, 20, 91, 41))
        self.newInductor.setObjectName("newInductor")
        self.resInd1_label = QtWidgets.QLabel(self.Inductors)
        self.resInd1_label.setGeometry(QtCore.QRect(350, 80, 191, 31))
        self.resInd1_label.setObjectName("resInd1_label")
        self.resInd1 = QtWidgets.QLineEdit(self.Inductors)
        self.resInd1.setGeometry(QtCore.QRect(380, 120, 113, 31))
        self.resInd1.setObjectName("resInd1")
        Tab.addTab(self.Inductors, "")
        self.Capacitors = QtWidgets.QWidget()
        self.Capacitors.setObjectName("Capacitors")
        self.capacitor1_label = QtWidgets.QLabel(self.Capacitors)
        self.capacitor1_label.setGeometry(QtCore.QRect(20, 110, 101, 31))
        self.capacitor1_label.setObjectName("capacitor1_label")
        self.valCap1_label = QtWidgets.QLabel(self.Capacitors)
        self.valCap1_label.setGeometry(QtCore.QRect(170, 80, 131, 31))
        self.valCap1_label.setObjectName("valCap1_label")
        self.newCapacitor = QtWidgets.QPushButton(self.Capacitors)
        self.newCapacitor.setGeometry(QtCore.QRect(10, 20, 91, 41))
        self.newCapacitor.setObjectName("newCapacitor")
        self.pairCap1_label = QtWidgets.QLabel(self.Capacitors)
        self.pairCap1_label.setGeometry(QtCore.QRect(170, 169, 81, 31))
        self.pairCap1_label.setObjectName("pairCap1_label")
        self.pairCap1 = QtWidgets.QLineEdit(self.Capacitors)
        self.pairCap1.setGeometry(QtCore.QRect(170, 210, 113, 31))
        self.pairCap1.setObjectName("pairCap1")
        self.poleCap1_label = QtWidgets.QLabel(self.Capacitors)
        self.poleCap1_label.setGeometry(QtCore.QRect(380, 169, 81, 31))
        self.poleCap1_label.setObjectName("poleCap1_label")
        self.valCap1 = QtWidgets.QLineEdit(self.Capacitors)
        self.valCap1.setGeometry(QtCore.QRect(170, 120, 113, 31))
        self.valCap1.setObjectName("valCap1")
        self.poleCap1 = QtWidgets.QLineEdit(self.Capacitors)
        self.poleCap1.setGeometry(QtCore.QRect(380, 210, 113, 31))
        self.poleCap1.setObjectName("poleCap1")
        Tab.addTab(self.Capacitors, "")
        self.Customer = QtWidgets.QWidget()
        self.Customer.setObjectName("Customer")
        self.r60Cus1 = QtWidgets.QLineEdit(self.Customer)
        self.r60Cus1.setGeometry(QtCore.QRect(170, 110, 113, 31))
        self.r60Cus1.setObjectName("r60Cus1")
        self.dwnLengthCus1 = QtWidgets.QLineEdit(self.Customer)
        self.dwnLengthCus1.setGeometry(QtCore.QRect(1210, 110, 113, 31))
        self.dwnLengthCus1.setObjectName("dwnLengthCus1")
        self.sec1IndCus1 = QtWidgets.QLineEdit(self.Customer)
        self.sec1IndCus1.setGeometry(QtCore.QRect(690, 210, 113, 31))
        self.sec1IndCus1.setObjectName("sec1IndCus1")
        self.primIndCus1_label = QtWidgets.QLabel(self.Customer)
        self.primIndCus1_label.setGeometry(QtCore.QRect(400, 170, 181, 31))
        self.primIndCus1_label.setObjectName("primIndCus1_label")
        self.sec2IndCus1 = QtWidgets.QLineEdit(self.Customer)
        self.sec2IndCus1.setGeometry(QtCore.QRect(950, 210, 113, 31))
        self.sec2IndCus1.setObjectName("sec2IndCus1")
        self.dwnLengthCus1_label = QtWidgets.QLabel(self.Customer)
        self.dwnLengthCus1_label.setGeometry(QtCore.QRect(1190, 70, 161, 31))
        self.dwnLengthCus1_label.setObjectName("dwnLengthCus1_label")
        self.turnCus1 = QtWidgets.QLineEdit(self.Customer)
        self.turnCus1.setGeometry(QtCore.QRect(170, 210, 113, 31))
        self.turnCus1.setObjectName("turnCus1")
        self.r60Cus1_label = QtWidgets.QLabel(self.Customer)
        self.r60Cus1_label.setGeometry(QtCore.QRect(180, 70, 91, 31))
        self.r60Cus1_label.setObjectName("r60Cus1_label")
        self.resCus1 = QtWidgets.QLineEdit(self.Customer)
        self.resCus1.setGeometry(QtCore.QRect(430, 110, 113, 31))
        self.resCus1.setObjectName("resCus1")
        self.customer1_label = QtWidgets.QLabel(self.Customer)
        self.customer1_label.setGeometry(QtCore.QRect(20, 100, 91, 41))
        self.customer1_label.setObjectName("customer1_label")
        self.primIndCus1 = QtWidgets.QLineEdit(self.Customer)
        self.primIndCus1.setGeometry(QtCore.QRect(430, 210, 113, 31))
        self.primIndCus1.setObjectName("primIndCus1")
        self.dwnIndCus1_label = QtWidgets.QLabel(self.Customer)
        self.dwnIndCus1_label.setGeometry(QtCore.QRect(910, 70, 211, 31))
        self.dwnIndCus1_label.setObjectName("dwnIndCus1_label")
        self.sec1IndCus1_label = QtWidgets.QLabel(self.Customer)
        self.sec1IndCus1_label.setGeometry(QtCore.QRect(650, 170, 211, 31))
        self.sec1IndCus1_label.setObjectName("sec1IndCus1_label")
        self.sec2IndCus1_label = QtWidgets.QLabel(self.Customer)
        self.sec2IndCus1_label.setGeometry(QtCore.QRect(900, 170, 221, 31))
        self.sec2IndCus1_label.setObjectName("sec2IndCus1_label")
        self.brkCus1_label = QtWidgets.QLabel(self.Customer)
        self.brkCus1_label.setGeometry(QtCore.QRect(660, 70, 181, 31))
        self.brkCus1_label.setObjectName("brkCus1_label")
        self.turnCus1_label = QtWidgets.QLabel(self.Customer)
        self.turnCus1_label.setGeometry(QtCore.QRect(140, 170, 181, 31))
        self.turnCus1_label.setObjectName("turnCus1_label")
        self.brkCus1 = QtWidgets.QLineEdit(self.Customer)
        self.brkCus1.setGeometry(QtCore.QRect(690, 110, 113, 31))
        self.brkCus1.setObjectName("brkCus1")
        self.newCustomer = QtWidgets.QPushButton(self.Customer)
        self.newCustomer.setGeometry(QtCore.QRect(10, 20, 91, 41))
        self.newCustomer.setObjectName("newCustomer")
        self.dwnIndCus1 = QtWidgets.QLineEdit(self.Customer)
        self.dwnIndCus1.setGeometry(QtCore.QRect(950, 110, 113, 31))
        self.dwnIndCus1.setObjectName("dwnIndCus1")
        self.resCus1_label = QtWidgets.QLabel(self.Customer)
        self.resCus1_label.setGeometry(QtCore.QRect(390, 70, 191, 31))
        self.resCus1_label.setObjectName("resCus1_label")
        self.servIndCus1 = QtWidgets.QLineEdit(self.Customer)
        self.servIndCus1.setGeometry(QtCore.QRect(1210, 210, 113, 31))
        self.servIndCus1.setText("")
        self.servIndCus1.setObjectName("servIndCus1")
        self.servIndCus1_label = QtWidgets.QLabel(self.Customer)
        self.servIndCus1_label.setGeometry(QtCore.QRect(1120, 170, 351, 31))
        self.servIndCus1_label.setObjectName("servIndCus1_label")
        self.dropNCus1_label = QtWidgets.QLabel(self.Customer)
        self.dropNCus1_label.setGeometry(QtCore.QRect(380, 270, 241, 31))
        self.dropNCus1_label.setObjectName("dropNCus1_label")
        self.dropPCus1 = QtWidgets.QLineEdit(self.Customer)
        self.dropPCus1.setGeometry(QtCore.QRect(170, 310, 113, 31))
        self.dropPCus1.setObjectName("dropPCus1")
        self.dropNCus1 = QtWidgets.QLineEdit(self.Customer)
        self.dropNCus1.setGeometry(QtCore.QRect(430, 310, 113, 31))
        self.dropNCus1.setObjectName("dropNCus1")
        self.dropLengthCus1 = QtWidgets.QLineEdit(self.Customer)
        self.dropLengthCus1.setGeometry(QtCore.QRect(690, 310, 113, 31))
        self.dropLengthCus1.setObjectName("dropLengthCus1")
        self.dropLengthCus1_label = QtWidgets.QLabel(self.Customer)
        self.dropLengthCus1_label.setGeometry(QtCore.QRect(660, 270, 181, 31))
        self.dropLengthCus1_label.setObjectName("dropLengthCus1_label")
        self.dropPCus1_label = QtWidgets.QLabel(self.Customer)
        self.dropPCus1_label.setGeometry(QtCore.QRect(110, 270, 231, 31))
        self.dropPCus1_label.setObjectName("dropPCus1_label")
        self.poleCus1_label = QtWidgets.QLabel(self.Customer)
        self.poleCus1_label.setGeometry(QtCore.QRect(430, 380, 121, 21))
        self.poleCus1_label.setObjectName("poleCus1_label")
        self.pairCus1 = QtWidgets.QLineEdit(self.Customer)
        self.pairCus1.setGeometry(QtCore.QRect(170, 410, 113, 31))
        self.pairCus1.setText("")
        self.pairCus1.setObjectName("pairCus1")
        self.poleCus1 = QtWidgets.QLineEdit(self.Customer)
        self.poleCus1.setGeometry(QtCore.QRect(430, 410, 113, 31))
        self.poleCus1.setText("")
        self.poleCus1.setObjectName("poleCus1")
        self.pairCus1_label = QtWidgets.QLabel(self.Customer)
        self.pairCus1_label.setGeometry(QtCore.QRect(170, 380, 111, 21))
        self.pairCus1_label.setObjectName("pairCus1_label")
        Tab.addTab(self.Customer, "")
        self.Pipegap = QtWidgets.QWidget()
        self.Pipegap.setObjectName("Pipegap")
        self.pipegap1_label = QtWidgets.QLabel(self.Pipegap)
        self.pipegap1_label.setGeometry(QtCore.QRect(30, 110, 81, 31))
        self.pipegap1_label.setObjectName("pipegap1_label")
        self.pairPipe1_label = QtWidgets.QLabel(self.Pipegap)
        self.pairPipe1_label.setGeometry(QtCore.QRect(170, 160, 91, 20))
        self.pairPipe1_label.setObjectName("pairPipe1_label")
        self.resPipe1 = QtWidgets.QLineEdit(self.Pipegap)
        self.resPipe1.setGeometry(QtCore.QRect(360, 110, 113, 31))
        self.resPipe1.setObjectName("resPipe1")
        self.cfoPipe1_label = QtWidgets.QLabel(self.Pipegap)
        self.cfoPipe1_label.setGeometry(QtCore.QRect(120, 70, 221, 31))
        self.cfoPipe1_label.setObjectName("cfoPipe1_label")
        self.polePipe1 = QtWidgets.QLineEdit(self.Pipegap)
        self.polePipe1.setGeometry(QtCore.QRect(360, 190, 113, 31))
        self.polePipe1.setObjectName("polePipe1")
        self.newPipegap = QtWidgets.QPushButton(self.Pipegap)
        self.newPipegap.setGeometry(QtCore.QRect(10, 20, 91, 41))
        self.newPipegap.setObjectName("newPipegap")
        self.pairPipe1 = QtWidgets.QLineEdit(self.Pipegap)
        self.pairPipe1.setGeometry(QtCore.QRect(170, 190, 113, 31))
        self.pairPipe1.setObjectName("pairPipe1")
        self.resPipe1_label = QtWidgets.QLabel(self.Pipegap)
        self.resPipe1_label.setGeometry(QtCore.QRect(340, 69, 181, 31))
        self.resPipe1_label.setObjectName("resPipe1_label")
        self.cfoPipe1 = QtWidgets.QLineEdit(self.Pipegap)
        self.cfoPipe1.setGeometry(QtCore.QRect(170, 110, 113, 31))
        self.cfoPipe1.setObjectName("cfoPipe1")
        self.polePipe1_label = QtWidgets.QLabel(self.Pipegap)
        self.polePipe1_label.setGeometry(QtCore.QRect(360, 160, 91, 20))
        self.polePipe1_label.setObjectName("polePipe1_label")
        Tab.addTab(self.Pipegap, "")

#        @pyqtSlot()
#        def simulate():
#            res = saveProject()
#
#            # No error during saving
#            if res == 0:
#                Simulate.simulateProject(openETran)
#
#        @pyqtSlot()
#        def saveProject():
#            # Read the structure in the GUI in case it changed
#            openETran = ReadStruct.read(self)
#
#            # Writes in JSON file
#            if openETran['name'] != '':
#                Save.saveProject(openETran, openETran['name'])
#                print('Project saved')
#                return 0
#            else:
#                print('Project must have a name.')
#                return 1
#
#        @pyqtSlot()
#        def loadProject():
#            openETran = Load.loadProject(self)
#
#        # Events linked to each pressed buttons
#        self.load.pressed.connect(loadProject)
#        self.save.pressed.connect(saveProject)
#        self.simButton.pressed.connect(simulate)

        self.retranslateUi(Tab)
        Tab.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Tab)

    def retranslateUi(self, Tab):
        _translate = QtCore.QCoreApplication.translate
        Tab.setWindowTitle(_translate("Tab", "OpenETran"))
        self.load.setText(_translate("Tab", "Load Project"))
        self.save.setText(_translate("Tab", "Save"))
        self.label.setText(_translate("Tab", "Project Name"))
        Tab.setTabText(Tab.indexOf(self.Project), _translate("Tab", "Project"))
        self.sysView_label.setText(_translate("Tab", "System View :"))
        self.drawSystem.setText(_translate("Tab", "Draw"))
        Tab.setTabText(Tab.indexOf(self.SystemView), _translate("Tab", "System View"))
        self.numCond_label.setText(_translate("Tab", "Number of conductors"))
        self.numPoles_label.setText(_translate("Tab", "Number of poles"))
        self.lineSpan_label.setText(_translate("Tab", "Line Span (m)"))
        self.leftTerm_label.setText(_translate("Tab", "Left Termination (y/n)"))
        self.rightTerm_label.setText(_translate("Tab", "Right Termination (y/n)"))
        self.timeStep_label.setText(_translate("Tab", "Time step (s)"))
        self.simMax_label.setText(_translate("Tab", "Simulation Max Time (s)"))
        self.simButton.setText(_translate("Tab", "Simulate !"))
        Tab.setTabText(Tab.indexOf(self.Simulation), _translate("Tab", "Simulation"))
        self.cond1_label.setText(_translate("Tab", "Conductor 1"))
        self.height_label.setText(_translate("Tab", "Height (m)"))
        self.horPos_label.setText(_translate("Tab", "Horizontal Position (m)"))
        self.rad_label.setText(_translate("Tab", "Radius (m)"))
        self.voltBias_label.setText(_translate("Tab", "Voltage Bias (V)"))
        self.cond2_label.setText(_translate("Tab", "Conductor 2"))
        self.cond3_label.setText(_translate("Tab", "Conductor 3"))
        self.cond4_label.setText(_translate("Tab", "Conductor 4 - Neutral"))
        self.condLabel_label.setText(_translate("Tab", "Label (Opt.)"))
        Tab.setTabText(Tab.indexOf(self.Conductor), _translate("Tab", "Conductor"))
        self.ground1_label.setText(_translate("Tab", "Ground 1"))
        self.r60Ground_label.setText(_translate("Tab", "R60 (Ohm)"))
        self.resistGround_label.setText(_translate("Tab", "Soil Resistivity (Ohm / m)"))
        self.brkGround_label.setText(_translate("Tab", "Soil Brk Gradient (V/m)"))
        self.dwnLGround_label.setText(_translate("Tab", "Downlead Inductance (H/m)"))
        self.dwnLengthGround_label.setText(_translate("Tab", "Length of downlead (m)"))
        self.radGround_label.setText(_translate("Tab", "Counterpoise Radius (m)"))
        self.depthGround_label.setText(_translate("Tab", "Counterpoise Depth (m)"))
        self.lengthGround_label.setText(_translate("Tab", "Counterpoise Length (m)"))
        self.numSegGround_label.setText(_translate("Tab", "Number of Segments"))
        self.permGround_label.setText(_translate("Tab", "Soil Relative Permittivity"))
        self.pairGround_label.setText(_translate("Tab", "Pairs"))
        self.poleGround_label.setText(_translate("Tab", "Poles"))
        self.newGround.setText(_translate("Tab", "New"))
        Tab.setTabText(Tab.indexOf(self.Ground), _translate("Tab", "Ground"))
        self.crestSurge_label.setText(_translate("Tab", "Crest Current (A)"))
        self.frontSurge_label.setText(_translate("Tab", "30 - 90 Front Time (s)"))
        self.tailSurge_label.setText(_translate("Tab", "50 % Tail Time (s)"))
        self.startSurge_label.setText(_translate("Tab", "Surge Starting Time (s)"))
        self.maxSurge_label.setText(_translate("Tab", "Max Current Steepness (pu)"))
        Tab.setTabText(Tab.indexOf(self.Surge), _translate("Tab", "Surge"))
        self.crestSteep_label.setText(_translate("Tab", "Crest Current (A)"))
        self.frontSteep_label.setText(_translate("Tab", "30 - 90 Front Time (s)"))
        self.startSteep_label.setText(_translate("Tab", "Surge Starting Time (s)"))
        self.tailSteep_label.setText(_translate("Tab", "50 % Tail Time (s)"))
        self.maxSteep_label.setText(_translate("Tab", "Max Current Steepness (pu)"))
        Tab.setTabText(Tab.indexOf(self.Steepfront), _translate("Tab", "Steepfront"))
        self.newArrester.setText(_translate("Tab", "New"))
        self.arrester1_label.setText(_translate("Tab", "Arrester 1"))
        self.spVoltArr1_label.setText(_translate("Tab", "Sparkover Voltage (V)"))
        self.tOnArr1_label.setText(_translate("Tab", "Turn-On Voltage (V)"))
        self.disArr1_label.setText(_translate("Tab", "Discharge Charact. Slope (Ohm)"))
        self.indArr1_label.setText(_translate("Tab", "Inductance of Lead (H/m)"))
        self.lengthArr1_label.setText(_translate("Tab", "Length of Lead (m)"))
        self.pairArr1_label.setText(_translate("Tab", "Pairs"))
        self.poleArr1_label.setText(_translate("Tab", "Poles"))
        Tab.setTabText(Tab.indexOf(self.Arrester), _translate("Tab", "Arrester"))
        self.refVoltArrb1_label.setText(_translate("Tab", "Reference Voltage (pu)"))
        self.poleArrb1_label.setText(_translate("Tab", "Poles"))
        self.indArrb1_label.setText(_translate("Tab", "Inductance of Lead (H/m)"))
        self.newArrbez.setText(_translate("Tab", "New"))
        self.arrbez1_label.setText(_translate("Tab", "Arrbez 1"))
        self.lengthArrb1_label.setText(_translate("Tab", "Length of Lead (m)"))
        self.pairArrb1_label.setText(_translate("Tab", "Pairs"))
        self.spVoltArrb1_label.setText(_translate("Tab", "Sparkover Voltage (V)"))
        self.disVoltArrb1_label.setText(_translate("Tab", "10kA Crest Dis Voltage (V)"))
        self.plotArrb1_label.setText(_translate("Tab", "Plot Arrester Current"))
        self.plotArrb1.setItemText(0, _translate("Tab", "Yes"))
        self.plotArrb1.setItemText(1, _translate("Tab", "No"))
        Tab.setTabText(Tab.indexOf(self.Arrbez), _translate("Tab", "Arrbez"))
        self.newInsulator.setText(_translate("Tab", "New"))
        self.insulator1_label.setText(_translate("Tab", "Insulator 1"))
        self.minVoltIns1_label.setText(_translate("Tab", "Min. Volt for Desctructive Effect"))
        self.minDesIns1_label.setText(_translate("Tab", "Min. Destructive Effect to cause flashover"))
        self.expIns1_label.setText(_translate("Tab", "Exponent for Desctructive Effect"))
        self.cfoIns1_label.setText(_translate("Tab", "CFO (V)"))
        self.pairIns1_label.setText(_translate("Tab", "Pairs"))
        self.poleIns1_label.setText(_translate("Tab", "Poles"))
        Tab.setTabText(Tab.indexOf(self.Insulator), _translate("Tab", "Insulator"))
        self.newLPM.setText(_translate("Tab", "New"))
        self.pairLPM1_label.setText(_translate("Tab", "Pairs"))
        self.poleLPM1_label.setText(_translate("Tab", "Poles"))
        self.cfoLPM1_label.setText(_translate("Tab", "CFO / BIL (V)"))
        self.lpm1_label.setText(_translate("Tab", "LPM 1"))
        self.cstLPM1_label.setText(_translate("Tab", "LPM Constant Kl"))
        self.brkLPM1_label.setText(_translate("Tab", "Min. Brk Gradient (V/m)"))
        Tab.setTabText(Tab.indexOf(self.LPM), _translate("Tab", "LPM"))
        self.meter1_label.setText(_translate("Tab", "Meter 1"))
        self.newMeter.setText(_translate("Tab", "New"))
        self.typeMeter1_label.setText(_translate("Tab", "Type"))
        self.typeMeter1.setItemText(0, _translate("Tab", "Voltage"))
        self.typeMeter1.setItemText(1, _translate("Tab", "Arrester Current"))
        self.typeMeter1.setItemText(2, _translate("Tab", "Pole Ground Current"))
        self.typeMeter1.setItemText(3, _translate("Tab", "Customer House Ground Current"))
        self.typeMeter1.setItemText(4, _translate("Tab", "Customer Tranformer X2 Terminal Current"))
        self.typeMeter1.setItemText(5, _translate("Tab", "PipeGap Discharge Current"))
        self.pairMeter1_label.setText(_translate("Tab", "Pairs"))
        self.poleMeter1_label.setText(_translate("Tab", "Poles"))
        Tab.setTabText(Tab.indexOf(self.Meters), _translate("Tab", "Meters"))
        self.valRes1_label.setText(_translate("Tab", "Value (Ohm)"))
        self.pairRes1_label.setText(_translate("Tab", "Pairs"))
        self.resistor1_label.setText(_translate("Tab", "Resistor 1"))
        self.poleRes1_label.setText(_translate("Tab", "Poles"))
        self.newResistor.setText(_translate("Tab", "New"))
        Tab.setTabText(Tab.indexOf(self.Resistors), _translate("Tab", "Resistors"))
        self.valInd1_label.setText(_translate("Tab", "Series Inductance (H)"))
        self.pairInd1_label.setText(_translate("Tab", "Pairs"))
        self.inductor1_label.setText(_translate("Tab", "Inductor 1"))
        self.poleInd1_label.setText(_translate("Tab", "Poles"))
        self.newInductor.setText(_translate("Tab", "New"))
        self.resInd1_label.setText(_translate("Tab", "Series Resistance (Ohm)"))
        Tab.setTabText(Tab.indexOf(self.Inductors), _translate("Tab", "Inductors"))
        self.capacitor1_label.setText(_translate("Tab", "Capacitor 1"))
        self.valCap1_label.setText(_translate("Tab", "Capacitance (F)"))
        self.newCapacitor.setText(_translate("Tab", "New"))
        self.pairCap1_label.setText(_translate("Tab", "Pairs"))
        self.poleCap1_label.setText(_translate("Tab", "Poles"))
        Tab.setTabText(Tab.indexOf(self.Capacitors), _translate("Tab", "Capacitors"))
        self.primIndCus1_label.setText(_translate("Tab", "Primary Inductance (H)"))
        self.dwnLengthCus1_label.setText(_translate("Tab", "Downlead length (m)"))
        self.r60Cus1_label.setText(_translate("Tab", "R60 (Ohm)"))
        self.customer1_label.setText(_translate("Tab", "Customer 1"))
        self.dwnIndCus1_label.setText(_translate("Tab", "Downlead Inductance (H/m)"))
        self.sec1IndCus1_label.setText(_translate("Tab", "Secondary 1 Inductance (H)"))
        self.sec2IndCus1_label.setText(_translate("Tab", "Secondary 2 Inductance (H)"))
        self.brkCus1_label.setText(_translate("Tab", "Soil Brk Gradient (V/m)"))
        self.turnCus1_label.setText(_translate("Tab", "Transformer Turns Ratio"))
        self.newCustomer.setText(_translate("Tab", "New"))
        self.resCus1_label.setText(_translate("Tab", "Soil Resistivity (Ohm / m)"))
        self.servIndCus1_label.setText(_translate("Tab", "Service drop common-mode inductance (H/m)"))
        self.dropNCus1_label.setText(_translate("Tab", "Service drop neutral cond radius"))
        self.dropLengthCus1_label.setText(_translate("Tab", "Service drop length (m)"))
        self.dropPCus1_label.setText(_translate("Tab", "Service drop phase cond radius"))
        self.poleCus1_label.setText(_translate("Tab", "Poles"))
        self.pairCus1_label.setText(_translate("Tab", "Pairs"))
        Tab.setTabText(Tab.indexOf(self.Customer), _translate("Tab", "Customer"))
        self.pipegap1_label.setText(_translate("Tab", "Pipegap 1"))
        self.pairPipe1_label.setText(_translate("Tab", "Pairs"))
        self.cfoPipe1_label.setText(_translate("Tab", "CFO between conductors (V)"))
        self.newPipegap.setText(_translate("Tab", "New"))
        self.resPipe1_label.setText(_translate("Tab", "Series resistance (Ohm)"))
        self.polePipe1_label.setText(_translate("Tab", "Poles"))
        Tab.setTabText(Tab.indexOf(self.Pipegap), _translate("Tab", "Pipegap"))


if __name__ == "__main__":
    import sys

    openETran = OrderedDict()

    app = QtWidgets.QApplication(sys.argv)
    Tab = QtWidgets.QTabWidget()
    ui = Ui_Tab()
    ui.setupUi(Tab)
    Tab.show()
    sys.exit(app.exec_())

